
# Build settings
[build]
  publish = "dist"
  command = "npm run build"

# Set cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Set security and cache headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.gpteng.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; connect-src 'self' https://*.netlify.app https://api.netlify.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; form-action 'self'; frame-ancestors 'none'; base-uri 'self'; object-src 'none';"

# Set cache headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Set cache headers for service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirects for SPA and success page
[[redirects]]
  from = "/takk"
  to = "/takk.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Explicit forms configuration
[build.environment]
  NETLIFY_FORMS = "true"

# Enable form detection explicitly
[build.processing]
  skip_processing = false

# Form processing explicitly enabled
[build.processing.forms]
  enabled = true

# Optimize images
[build.processing.images]
  compress = true

# Bundle and minify assets
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Enable Lighthouse plugin
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Custom domain configuration
[context.production]
  domain = "camphercommunications.no"

# Form notifications configuration
[[forms.contact.notifications]]
  to = "kontakt@camphercommunications.no"
  from = "noreply@camphercommunications.no"
  subject = "Ny melding fra camphercommunications.no"
