
# Build settings
[build]
  publish = "dist"
  command = "npm run build"

# Set correct content type for JavaScript files
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

# Set correct content type for CSS files
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

# Set security and cache headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # Fix CSP to allow data URLs and fonts
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.gpteng.co 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com data:; connect-src 'self' https://*.netlify.app https://api.netlify.com https://fonts.googleapis.com https://fonts.gstatic.com https://cdn.gpteng.co; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https://www.google.com https://maps.googleapis.com; form-action 'self'; frame-src 'self' https://www.google.com; frame-ancestors 'none'; base-uri 'self'; object-src 'none';"
    Cross-Origin-Opener-Policy = "same-origin"

# Set cache headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Set cache headers for service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Order redirects correctly - assets first, then specific routes, then fallback
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200

[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200

[[redirects]]
  from = "/takk"
  to = "/takk.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Explicit forms configuration
[build.environment]
  NETLIFY_FORMS = "true"

# Enable form detection explicitly
[build.processing]
  skip_processing = false

# Form processing explicitly enabled
[build.processing.forms]
  enabled = true

# Optimize images
[build.processing.images]
  compress = true

# Bundle and minify assets
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Enable Lighthouse plugin
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Custom domain configuration
[context.production]
  domain = "camphercommunications.no"

# Form notifications configuration
[[forms]]
  name = "contact"

  [forms.notifications]
    to = "kontakt@camphercommunications.no"
    from = "noreply@camphercommunications.no"
    subject = "Ny melding fra camphercommunications.no"
