
[build]
  publish = "dist"
  command = "npm run build"

# Set cache headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Set cache headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Set cache headers for service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Set up redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set up form submissions - enable Netlify forms
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true

# Optimize images
[build.processing.images]
  compress = true

# Enable HTTP/2 for faster delivery
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Enable brotli compression for smaller files
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Enable security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
